### ISSUE TITLE
Failed python compilation

### ISSUE THREAD

**Issue by loopless** [FreeCAD/FreeCAD-LibPack#30]
- I checked the README
- I made sure winbison and 7z are in the PATH
- I have  a VS2022 command prompt open

D:\free_cad_build\FreeCAD-LibPack>python create_libpack.py
Cloning https://github.com/python/cpython.git at v3.12.4
...... etc then...

Building python
Traceback (most recent call last):
  File "create_libpack.py", line 287, in <module>
    compiler.compile_all()
  File "D:\free_cad_build\FreeCAD-LibPack\compile_all.py", line 208, in compile_all
    build_function(item)
  File "D:\free_cad_build\FreeCAD-LibPack\compile_all.py", line 240, in build_python
    subprocess.run(
  File "D:\FreeCAD_0.20\FreeCAD_0.20\bin\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\FreeCAD_0.20\FreeCAD_0.20\bin\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\FreeCAD_0.20\FreeCAD_0.20\bin\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

I have checked that D:\free_cad_build\FreeCAD-LibPack\working\python\PCbuild\build.bat exists and can be executed manually
When running the build.bat manually I got the error

  Regenerate Global Objects
   not changed: d:\free_cad_build\FreeCAD-LibPack\working\python\Include\internal\pycore_global_strings.h
  not changed: d:\free_cad_build\FreeCAD-LibPack\working\python\Include\internal\pycore_runtime_init_generated.h
  not changed: d:\free_cad_build\FreeCAD-LibPack\working\python\Include\internal\pycore_unicodeobject_generated.h
   not changed: d:\free_cad_build\FreeCAD-LibPack\working\python\Include\internal\pycore_global_objects_fini_generated.h
  Traceback (most recent call last):
    File "d:\free_cad_build\FreeCAD-LibPack\working\python\Tools\build\generate_sbom.py", line 44, in <module>
      class PackageFiles(typing.NamedTuple):
    File "d:\free_cad_build\FreeCAD-LibPack\working\python\Tools\build\generate_sbom.py", line 46, in PackageFiles
      include: list[str] | None
  TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

**Comment by loopless** [comment]
The fix to. the problem above build problem was to set HOST_PYTHON to point to a version of python >=3.10
For example

set HOST_PYTHON=C:\Python312\python.exe
